# Generated by Django 3.2.13 on 2023-04-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocknewsai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='create_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
